// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_5WUpoSBuQ-1OBuu7L8ffsKJbDXw8Ro',
    appId: '1:80253420074:web:aa9ba74af2aae76602f953',
    messagingSenderId: '80253420074',
    projectId: 'recyclify-4a523',
    authDomain: 'recyclify-4a523.firebaseapp.com',
    storageBucket: 'recyclify-4a523.appspot.com',
    measurementId: 'G-R5WEQD7TD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8XWvJbYDX1Up78X1bP10C_MNkwdfycQ',
    appId: '1:80253420074:android:5b21db6496f091ec02f953',
    messagingSenderId: '80253420074',
    projectId: 'recyclify-4a523',
    storageBucket: 'recyclify-4a523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQCJzLI810x5JCo3Ayk_VNbT-0Oa1KAI',
    appId: '1:80253420074:ios:511df412e28cccbc02f953',
    messagingSenderId: '80253420074',
    projectId: 'recyclify-4a523',
    storageBucket: 'recyclify-4a523.appspot.com',
    iosBundleId: 'com.example.recyclify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQCJzLI810x5JCo3Ayk_VNbT-0Oa1KAI',
    appId: '1:80253420074:ios:34e9c0fe5607032002f953',
    messagingSenderId: '80253420074',
    projectId: 'recyclify-4a523',
    storageBucket: 'recyclify-4a523.appspot.com',
    iosBundleId: 'com.example.recyclify.RunnerTests',
  );
}
